# Generated by Django 2.2.3 on 2019-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.ImageField(upload_to='')),
                ('about', models.ImageField(upload_to='')),
                ('services', models.ImageField(upload_to='')),
                ('team', models.ImageField(upload_to='')),
                ('portfolio', models.ImageField(upload_to='')),
                ('contact', models.ImageField(upload_to='')),
            ],
        ),
    ]
