# Generated by Django 2.2.3 on 2019-10-25 06:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', tinymce.models.HTMLField()),
                ('description', tinymce.models.HTMLField()),
                ('requirements', tinymce.models.HTMLField()),
                ('skills', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='events')),
                ('description', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='career',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='events',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
