# Generated by Django 2.2.3 on 2019-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='how_we_worl',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='bg_image',
            field=models.ImageField(default=None, upload_to='about'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='how_we_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='about',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='contact',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='portfolio',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='services',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='team',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(upload_to='sitesetting'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='team'),
        ),
    ]
