# Generated by Django 2.2.3 on 2019-10-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0003_auto_20191025_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='how_we_work',
        ),
    ]
