# Generated by Django 2.2.3 on 2019-10-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0004_remove_aboutus_how_we_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='number2',
            field=models.CharField(max_length=15),
        ),
    ]
