# Generated by Django 2.2.3 on 2019-11-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0005_auto_20191031_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
    ]
