# Generated by Django 2.2.3 on 2019-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0005_auto_20190930_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='best_for',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
