# Generated by Django 2.2.3 on 2019-10-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0006_aboutus_best_for'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
