# Generated by Django 2.2.3 on 2019-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0006_auto_20191112_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='how_we_work',
            field=models.ImageField(default=None, upload_to='about'),
        ),
    ]
