# Generated by Django 2.2.3 on 2019-10-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0007_auto_20191001_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Messages submitted from contact form'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio of our work'},
        ),
        migrations.AlterModelOptions(
            name='servicedesc',
            options={'verbose_name_plural': 'Description in the first section of service page'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': 'Types of services'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name_plural': 'Site Setting'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Our Team'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials of clients'},
        ),
    ]
