# Generated by Django 2.2.3 on 2019-10-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0008_auto_20191003_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='number2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
    ]
