# Generated by Django 2.2.3 on 2019-10-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djgroup', '0010_portfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='what_we_do',
        ),
        migrations.AddField(
            model_name='banner',
            name='about_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='contact_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='index_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='portfolio_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='services_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='team_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='how_we_work',
            field=models.ImageField(default=None, upload_to='about'),
        ),
    ]
